services:
  yoghurt-backend:
    build: .
    container_name: yoghurt_backend
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/yoghurt
    networks:
      - shared_dev_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  shared_dev_network:
    external: true
